import { nanoid } from "nanoid";
import { generateVendorCode } from "../../helper";
import iphoneSierraBlue from "../../assets/iphoneSierraBlue.svg";
import iphoneBlue from "../../assets/iphoneBlue.svg";
import iphoneBlack from "../../assets/iphoneBlack.svg";
import iphoneGraphiteBlack from "../../assets/iphoneGraphiteBlack.svg";
import colorsCaseApple from "../../assets/colorsCaseApple.svg";
import caseApple from "../../assets/caseApple.svg";
import appleScreens from "../../assets/appleScreens.svg";
import IMac from "../../assets/IMacCategory.svg";
import iPadCategory from "../../assets/iPadCategory.svg";
import appleWatchCategory from "../../assets/appleWatchCategory.svg";

import samsungScreens from "../../assets/samsungScreens.svg";

import { IProductCategory } from "../../types";
export const listProduct: IProductCategory = {
  Iphone: [
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: true,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: true,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneBlack,
    },
  ],
  IPad: [
    {
      id: nanoid(),
      name: "IPad Mini",
      price: 300,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "Mini",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iPadCategory,
    },
    {
      id: nanoid(),
      name: "IPad Mini",
      price: 400,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "Mini",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iPadCategory,
    },
    {
      id: nanoid(),
      name: "IPad Air",
      price: 400,
      inStock: true,
      isPopular: true,
      color: "Red",
      model: "Air",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iPadCategory,
    },
    {
      id: nanoid(),
      name: "IPad Air",
      price: 600,
      inStock: true,
      isPopular: true,
      color: "Yellow",
      model: "Air",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iPadCategory,
    },
    {
      id: nanoid(),
      name: "IPad Pro",
      price: 900,
      inStock: true,
      isPopular: true,
      color: "Red",
      model: "Pro",
      storage: "512 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iPadCategory,
    },
    {
      id: nanoid(),
      name: "IPad Pro",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Green",
      model: "Pro",
      storage: "1 TB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iPadCategory,
    },
  ],
  ["Android Smartphones"]: [
    {
      id: nanoid(),
      name: "Samsung",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "Samsung",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Samsung",
      price: 1900,
      inStock: true,
      isPopular: true,
      color: "Red",
      model: "Samsung",
      storage: "512 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Xiaomi",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "Xiaomi",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Xiaomi",
      price: 2200,
      inStock: true,
      isPopular: true,
      color: "Yellow",
      model: "Xiaomi",
      storage: "512 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Huawei",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "Huawei",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Huawei",
      price: 2200,
      inStock: true,
      isPopular: true,
      color: "Green",
      model: "Huawei",
      storage: "512 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Oppo",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "Oppo",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Oppo",
      price: 2200,
      inStock: true,
      isPopular: true,
      color: "Yellow",
      model: "Oppo",
      storage: "512 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Vivo",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "Vivo",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Vivo",
      price: 2200,
      inStock: true,
      isPopular: true,
      color: "Green",
      model: "Vivo",
      storage: "512 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: iphoneSierraBlue,
    },
  ],
  Accessories: [
    {
      id: nanoid(),
      name: "Silicone case overlay Original iPhone Silicone Case for iPhone 6 / 6s / 7 / 8 / Plus / X",
      price: 5,
      inStock: true,
      isPopular: false,
      model: "Case",
      color: "Red",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: colorsCaseApple,
    },
    {
      id: nanoid(),
      name: "Ultra-thin case for iPhone 5s/6/6s/7",
      price: 1,
      inStock: true,
      isPopular: false,
      model: "Case",
      color: "Black",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: caseApple,
    },
    {
      id: nanoid(),
      name: "HOCO Cool Radian Series (HD) 3D Shockproof Protective Glass for iPhone 6 / 6s / 7 / 8 / X / 11 / 12 / 13 / Plus / 16 ",
      price: 3,
      inStock: true,
      isPopular: false,
      model: "Screen Protector",
      color: "Yellow",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: samsungScreens,
    },
    {
      id: nanoid(),
      name: "HOCO Cool Zenith Series (HD) 3D Shockproof Glass Screen Protector for iPhone 6 / 6s / 7 / 8 / X / Plus...",
      price: 4,
      inStock: true,
      isPopular: false,
      model: "Screen Protector",
      color: "Yellow",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: appleScreens,
    },
    {
      id: nanoid(),
      name: "Silicone case overlay Original iPhone Silicone Case for iPhone 6 / 6s / 7 / 8 / Plus / X",
      price: 5,
      inStock: true,
      isPopular: false,
      model: "Screen Protector",
      color: "Blue",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: colorsCaseApple,
    },
    {
      id: nanoid(),
      name: "Silicone case overlay Original iPhone Silicone Case for iPhone 6 / 6s / 7 / 8 / Plus / X",
      price: 5,
      inStock: true,
      isPopular: false,
      model: "Case",
      color: "Black",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: colorsCaseApple,
    },
    {
      id: nanoid(),
      name: "Ultra-thin case for iPhone 5s/6/6s/7",
      price: 1,
      inStock: true,
      isPopular: false,
      model: "Case",
      color: "Black",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: caseApple,
    },
    {
      id: nanoid(),
      name: "HOCO Cool Radian Series (HD) 3D Shockproof Protective Glass for iPhone 6 / 6s / 7 / 8 / X / 11 / 12 / 13 / Plus / 16 ",
      price: 3,
      inStock: true,
      isPopular: false,
      model: "Screen Protector",
      color: "Blue",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: samsungScreens,
    },
    {
      id: nanoid(),
      name: "HOCO Cool Zenith Series (HD) 3D Shockproof Glass Screen Protector for iPhone 6 / 6s / 7 / 8 / X / Plus...",
      price: 4,
      inStock: true,
      isPopular: false,
      model: "Screen Protector",
      color: "Yellow",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: appleScreens,
    },
    {
      id: nanoid(),
      name: "Silicone case overlay Original iPhone Silicone Case for iPhone 6 / 6s / 7 / 8 / Plus / X",
      price: 5,
      inStock: true,
      isPopular: false,
      model: "Screen Protector",
      color: "Green",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: colorsCaseApple,
    },
    {
      id: nanoid(),
      name: "Silicone case overlay Original iPhone Silicone Case for iPhone 6 / 6s / 7 / 8 / Plus / X",
      price: 5,
      inStock: true,
      isPopular: false,
      model: "Case",
      color: "Green",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: colorsCaseApple,
    },
    {
      id: nanoid(),
      name: "Ultra-thin case for iPhone 5s/6/6s/7",
      price: 1,
      inStock: true,
      isPopular: false,
      model: "Case",
      color: "Yellow",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: caseApple,
    },
    {
      id: nanoid(),
      name: "HOCO Cool Radian Series (HD) 3D Shockproof Protective Glass for iPhone 6 / 6s / 7 / 8 / X / 11 / 12 / 13 / Plus / 16 ",
      price: 3,
      inStock: true,
      isPopular: false,
      model: "Screen Protector",
      color: "Blue",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: samsungScreens,
    },
    {
      id: nanoid(),
      name: "HOCO Cool Zenith Series (HD) 3D Shockproof Glass Screen Protector for iPhone 6 / 6s / 7 / 8 / X / Plus...",
      price: 4,
      inStock: true,
      isPopular: false,
      model: "Screen Protector",
      color: "Black",

      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: appleScreens,
    },
    {
      id: nanoid(),
      name: "Silicone case overlay Original iPhone Silicone Case for iPhone 6 / 6s / 7 / 8 / Plus / X",
      price: 5,
      inStock: true,
      isPopular: false,
      model: "Screen Protector",
      color: "Red",
      quantity: 1,
      vendorCode: generateVendorCode(),
      imgUrl: colorsCaseApple,
    },
  ],
  IMac: [
    {
      id: nanoid(),
      name: "IMac Mini",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Green",
      model: "Mini",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: IMac,
    },
    {
      id: nanoid(),
      name: "IMac Air",
      price: 2000,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "Air",
      storage: "256 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: IMac,
    },
    {
      id: nanoid(),
      name: "IMac Air",
      price: 3200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "Air",
      storage: "512 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: IMac,
    },
    {
      id: nanoid(),
      name: "IMac Pro",
      price: 4200,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "Pro",
      storage: "1 TB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: IMac,
    },
    {
      id: nanoid(),
      name: "IMac Pro",
      price: 3800,
      inStock: true,
      isPopular: true,
      color: "Green",
      model: "Pro",
      storage: "512 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: IMac,
    },
    {
      id: nanoid(),
      name: "IMac Mini",
      price: 1800,
      inStock: true,
      isPopular: true,
      color: "Green",
      model: "Mini",
      storage: "512 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: IMac,
    },
  ],
  ["Apple Watch"]: [
    {
      id: nanoid(),
      name: "Apple Watch Series 7",
      price: 400,
      inStock: true,
      isPopular: true,
      model: "Series 7",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: appleWatchCategory,
    },
    {
      id: nanoid(),
      name: "Apple Watch Series 7",
      price: 600,
      inStock: true,
      isPopular: true,
      model: "Series 7",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: appleWatchCategory,
    },
    {
      id: nanoid(),
      name: "Apple Watch SE",
      price: 300,
      inStock: true,
      isPopular: true,
      model: "SE",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: appleWatchCategory,
    },
    {
      id: nanoid(),
      name: "Apple Watch SE",
      price: 250,
      inStock: true,
      isPopular: true,
      model: "SE",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: appleWatchCategory,
    },
    {
      id: nanoid(),
      name: "Apple Watch Series 3",
      price: 350,
      inStock: true,
      isPopular: true,
      model: "Series 3",
      storage: "64 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: appleWatchCategory,
    },
    {
      id: nanoid(),
      name: "Apple Watch Series 3",
      price: 450,
      inStock: true,
      isPopular: true,
      model: "Series 3",
      storage: "128 GB",
      quantity: 1,
      vendorCode: generateVendorCode(),

      imgUrl: appleWatchCategory,
    },
  ],
};
