import { nanoid } from "nanoid";
import iphoneSierraBlue from "../../assets/iphoneSierraBlue.svg";
import iphoneBlue from "../../assets/iphoneBlue.svg";
import iphoneBlack from "../../assets/iphoneBlack.svg";
import iphoneGraphiteBlack from "../../assets/iphoneGraphiteBlack.svg";

import { IProductCategory } from "../../types";
export const listProduct: IProductCategory = {
  Iphone: [
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro 256GB Sierra Blue",
      price: 1420,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro",
      storage: "256 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Graphite",
      price: 1320,
      inStock: true,
      isPopular: true,
      color: "Black",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneGraphiteBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 Pro Max 128GB Sierra Blue",
      price: 1200,
      inStock: true,
      isPopular: true,
      color: "Blue",
      model: "13 Pro Max",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneSierraBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 13 128GB Blue",
      price: 920,
      inStock: true,
      isPopular: false,
      color: "Blue",
      model: "13",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlue,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 128GB Black",
      price: 600,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "128 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
    {
      id: nanoid(),
      name: "Apple iPhone 11 64GB Black",
      price: 700,
      inStock: false,
      isPopular: false,
      color: "Blue",
      model: "11",
      storage: "64 GB",
      quantity: 1,
      imgUrl: iphoneBlack,
    },
  ],
  IPad: [],
  Smartphones: [],
  Accessories: [],
  IMac: [],
  AppleWatch: [],
};
